---
- name: Remove Apache2 from server2
  hosts: server2
  become: yes

  tasks:
    - name: Ensure Apache2 is stopped
      ansible.builtin.systemd:
        name: apache2
        state: stopped
        enabled: no

    - name: Remove Apache2 package
      ansible.builtin.apt:
        name: apache2
        state: absent
        purge: yes  # Purge configuration files along with the package

    - name: Remove additional Apache2 modules and utilities (if any)
      ansible.builtin.apt:
        name:
          - apache2-bin
          - apache2-data
          - apache2-utils
        state: absent
        purge: yes

    - name: Remove Apache2 configuration directory
      ansible.builtin.file:
        path: /etc/apache2
        state: absent
        

    - name: Remove Apache2 log directory
      ansible.builtin.file:
        path: /var/log/apache2
        state: absent
        

    - name: Remove Apache2 default web root (if it exists)
      ansible.builtin.file:
        path: /var/www/html
        state: absent
        

    - name: Clean up any remaining Apache2 directories or files
      ansible.builtin.find:
        paths:
          - /etc/apache2
          - /var/log/apache2
          - /var/www/html
        
      ignore_errors: yes
